### ISSUE TITLE
오류신고 + 건의사항

### ISSUE THREAD

**Issue by bbbbb11112** [SION001122/Personalized-Web-streaming-#3]
건의 사항:
오른쪽에 트랙 리스트 스크롤 형식으로 추가

오류 내용:

1. User\어쩌구 하는 파일 경로 오류

2.음악 재생 오류(재생 버튼 비활성화되어있음)

다음은 Previous/Next Track 버튼 눌렀을떄 오류코드
[2024-11-28 22:32:29,868] ERROR in app: Exception on /public/none [GET]
Traceback (most recent call last):
  File "C:\Users\UserK\Desktop\PWP\.venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\UserK\Desktop\PWP\.venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\UserK\Desktop\PWP\.venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\UserK\Desktop\PWP\.venv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\UserK\Desktop\PWP\app(comment_kr).py", line 136, in error_album_cover
    [image.save](https://unsafelink.com/http://image.save)(image_byte_array, format="PNG")
  File "C:\Users\UserK\Desktop\PWP\.venv\lib\site-packages\PIL\Image.py", line 2605, in save
    save_handler(self, fp, filename)
  File "C:\Users\UserK\Desktop\PWP\.venv\lib\site-packages\PIL\PngImagePlugin.py", line 1371, in _save
    fp.write(_MAGIC)
AttributeError: 'NoneType' object has no attribute 'write'
127.0.0.1 - - [28/Nov/2024 22:32:29] "GET /public/none HTTP/1.1" 500 -

**Comment by bbbbb11112** [comment]
1*file*C:\Users\UserK\Desktop\PWP\audio\(Yuzuki Yukari)유즈키 유카리 -한쌍의 노래 [PV／자막] - Yukari린도.mp3.mp3
2*file*C:\Users\UserK\Desktop\PWP\audio\[Reniclus] 【Yuzuki Yukari V4 'Onn'】Hirari Hirari 【VOCALOID 4】 (C88ZCpidQyE).mp3.mp3
3*file*C:\Users\UserK\Desktop\PWP\audio\[Sera。] UNIVERSE／IA×flower (b_8Zf8Py-70).mp3.mp3
4*file*C:\Users\UserK\Desktop\PWP\audio\[Yuzuki Yukari] Hello How are You [Vocaloid 3] - Nestor Rodriguez.mp3.mp3
5*file*C:\Users\UserK\Desktop\PWP\audio\＊＊＊＊＊＊ - x0o0x_ - Topic.mp3.mp3
6*file*C:\Users\UserK\Desktop\PWP\audio\／ ／ ／／ ／ ／ - x0o0x_ - Topic.mp3.mp3

경로 입력 이런식으로 하는건 맞나요

**Comment by SION001122** [comment]
경로 입력은 
1*file*경로 가 맞습니다.

그리고 해당 오류는 none.png 즉 이미지 커버가 없거나 해석하지  못할 때 내보내줄 수 있는 이미지가 없기에 그런 문제가 생기는 것 같습니다. 우선 아무 사진이나 해당 이름으로 만들어서 놓으시면 해결은 될 것 입니다.

그림판으로 대충이나마 작성해서 none.png 파일 올려놓겠습니다.

**Comment by SION001122** [comment]
아, *이 붙어야 합니다. *

1 * file * 경로 입니다 이걸 붙이면 

1*file*경로가 되는 것 입니다.

**Comment by SION001122** [comment]
또한  image = Image.open(r"/Users/sinibida/mydoc/personalized-web-streaming/none.png") 이 부분을 실제 none.png가 있는 경로로 수정 해 주세요. 코드에서도  수정 해 놓겠습니다.

**Comment by bbbbb11112** [comment]
https://drive.google.com/file/d/1TP22QWdaZfgR7IFqgBQzGWTXRFaCyPNv/view?usp=sharing

코드 약간 수정했습니다

1. ffmpeg.exe 추가 (약280~310번 라인 사이에 ffmpeg을 ffmpeg.exe로 수정함)
2. reader.py추가 (audio 폴더에 음악 파일 넣고 reader.py 실행시 자동으로 audio_file_list.txt 업데이트)
3. 사이드바 추가
4. 기타 잡오류 수정

코드 감사합니다 ㅎㅎ
